
ANTICAPTCHA_API_KEY = '' # https://anti-captcha.com/
CHANGE_PROXY_URL = ''


REPEATS_ATTEMPTS = 5
ACCOUNT_TOO_NEW_ATTEMPTS = 1
ACCOUNT_UNAUTHORIZED_ATTEMPTS = 5
SLEEP_BETWEEN_TASKS = 0
SLEEP_AFTER_PROXY_CHANGING = 0
